# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
# SPDX-FileCopyrightText: 2024 Lucas De Marchi <lucas.de.marchi@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Build and Test

on:
  push:
    branches: [master, ci-test]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 2 * * 0"

permissions:
  contents: read

jobs:
  build:
    env:
      CC: ${{ matrix.compiler }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: 'gcc'
            container:
              name: 'alpine:latest'
              meson_setup: '-Ddocs=false -Db_sanitize=none'
          - compiler: 'gcc'
            container:
              name: 'archlinux:multilib-devel'
              multilib: 'true'
          - compiler: 'gcc'
            container:
              name: 'debian:unstable'
              multilib: 'true'
          - compiler: 'gcc'
            container:
              name: 'fedora:latest'
          - compiler: 'gcc'
            container:
              name: 'fedora:latest'
              meson_setup: '-Dxz=disabled -Ddlopen=all'
          - compiler: 'gcc'
            container:
              name: 'ubuntu:22.04'
              multilib: 'true'
          - compiler: 'gcc'
            container:
              name: 'ubuntu:22.04'
              multilib: 'true'
              meson_setup: '-Ddlopen=zstd,zlib'
          - compiler: 'gcc'
            container:
              name: 'ubuntu:24.04'
              multilib: 'true'

          - compiler: 'clang'
            container:
              name: 'alpine:latest'
              meson_setup: '-Ddocs=false -Db_sanitize=none'
          - compiler: 'clang'
            container:
              name: 'archlinux:multilib-devel'
              multilib: 'true'
          - compiler: 'clang'
            container:
              name: 'debian:unstable'
              multilib: 'true'
          - compiler: 'clang'
            container:
              name: 'fedora:latest'
          - compiler: 'clang'
            container:
              name: 'fedora:latest'
              meson_setup: '-Dxz=disabled -Ddlopen=all'
          - compiler: 'clang'
            container:
              name: 'ubuntu:22.04'
              multilib: 'true'
          - compiler: 'clang'
            container:
              name: 'ubuntu:22.04'
              multilib: 'true'
              meson_setup: '-Ddlopen=zstd,zlib'
          - compiler: 'clang'
            container:
              name: 'ubuntu:24.04'
              multilib: 'true'

    container:
      image: ${{ matrix.container.name }}

    steps:
      - name: Sparse checkout the local actions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/setup-alpine
        if: ${{ startsWith(matrix.container.name, 'alpine') }}
      - uses: ./.github/actions/setup-archlinux
        if: ${{ startsWith(matrix.container.name, 'archlinux') }}
      - uses: ./.github/actions/setup-debian
        if: ${{ startsWith(matrix.container.name, 'debian') }}
      - uses: ./.github/actions/setup-fedora
        if: ${{ startsWith(matrix.container.name, 'fedora') }}
      - uses: ./.github/actions/setup-ubuntu
        if: ${{ startsWith(matrix.container.name, 'ubuntu') }}

      - name: Checkout the whole project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set the environment
        run: |
          # The second checkout above claims to set safe.directory, yet it
          # doesn't quite work. Perhaps our double/sparse checkout is to blame?
          git config --global --add safe.directory '*'

          .github/print-kdir.sh >> "$GITHUB_ENV"

      - name: configure checks
        run: |
          should_fail() {
            rm -rf build-setup-test/
            if meson setup "$@" build-setup-test/; then
              echo Command was expected to fail, but was successful
              return 1
            fi
          }
          should_pass() {
            rm -rf build-setup-test/
            meson setup "$@" build-setup-test/
          }

          should_fail -D distconfdir=relative/
          should_fail -D moduledir=relative/
          should_fail -D dlopen=nonexistent
          should_fail -D xz=disabled -D dlopen=xz

          should_pass -D dlopen=xz
          should_pass -D dlopen=xz -D xz=enabled

      - name: configure
        run: mkdir build && cd build && meson setup --native-file ../build-dev.ini ${{ matrix.container.meson_setup }} . ..

      - name: build
        run: cd build && meson compile

      - name: test
        run: cd build && meson test || meson test --verbose

      - name: install
        run: cd build && DESTDIR=$PWD/inst meson install

      - name: distcheck
        run: cd build && meson dist

      - name: configure (32bit)
        if: ${{ matrix.container.multilib == 'true' }}
        run: |
          cross_options="-D zstd=disabled -D xz=disabled -D zlib=disabled -D openssl=disabled"
          CC="$CC -m32" meson setup $cross_options build32/

      - name: build (32bit)
        if: ${{ matrix.container.multilib == 'true' }}
        run: cd build32 && meson compile

      - name: test (32bit)
        if: ${{ matrix.container.multilib == 'true' }}
        run: cd build32 && meson test || meson test --verbose
